BallAverage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/', include(('equipos.urls', 'equipos'), namespace='equipos')),
    path('jugadores/', include(('jugadores.urls', 'jugadores'), namespace='jugadores')),
    path('estadisticas/', include(('stats.urls', 'estadisticas'), namespace='estadisticas')),
    path('partidos/', include(('partidos.urls', 'partidos'), namespace='partidos')),
    path('', include(('login.urls', 'login'), namespace='login')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jugadores/urls.py
'''Jugador Configuration'''
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
    path('', views.JugadorList.as_view(), name='list'),
    path('new', login_required(views.JugadorCreate.as_view()), name="new"),
    path('<pk>', login_required(views.JugadorDetail.as_view()), name="detail"),
    path('update/<pk>', views.JugadorUpdate.as_view(), name="update"),
    path('delete/<pk>', views.JugadorDelete.as_view(), name="delete"),
    path('fichaje/<pk>/', login_required(views.update_db_field), name="fichar"),
]

login/urls.py
'''Login Configuration'''
from django.urls import path, re_path, include
from django.conf.urls import url
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from . import views

urlpatterns = [
    path('', login, {'template_name':'index.html'}, name='login'),
    path('registrar/', views.RegistroUsuario.as_view(), name='registrar'),
    path('logout/', logout_then_login, name='logout'),
    path('reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html',
        'email_template_name':'registration/password_reset_email.html', 'post_reset_redirect':'login:password_reset_done'}, name='password_reset'),    
    path('reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'}, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', password_reset_confirm,
         {'template_name':'registration/password_reset_confirm.html','post_reset_redirect':'login:password_reset_complete'}, name='password_reset_confirm'),
    path('reset/done', password_reset_complete, {'template_name':'registration/password_reset_complete.html'}, name='password_reset_complete'),
]

jugadores/models.py
from django.db import models
from equipos.models import Equipo
from .utils import ChoiceEnum

# Create your models here.

class Posicion(models.Model):
    posicion = models.CharField(max_length=25)

    def __str__(self):
        return '{}'.format(self.posicion)

    class Meta:
        ordering = ('id',)
        verbose_name_plural = 'Posiciones'

class Jugador(models.Model):
    class Rols(ChoiceEnum):
        DEF = 'Defensor'
        TAP = 'Taponador'
        ATL = 'Atlético'
        ANOT = 'Anotador'
        PN = 'Penetrador'
        HC = 'Hombre clave'
        PR = 'Promesa'
        H6 = 'Sexto hombre'
        SUPL = 'Suplente'
        TMATE = 'Jugador de equipo'
        NOV = 'Novato'

    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    altura = models.DecimalField(max_digits=3, decimal_places=2)
    peso = models.DecimalField(max_digits=3, decimal_places=1)
    dorsal = models.IntegerField(default=0, blank=True)
    image = models.ImageField(blank=True, default='player.jpg')
    fnacimiento = models.DateField(null=True, blank=True)
    equipo = models.ForeignKey(Equipo, null=True, blank=True, on_delete=models.SET_NULL)
    funion = models.DateField(auto_now_add=True, null=True, blank=True)
    posicion = models.ForeignKey(Posicion, null=True, blank=True, on_delete=models.SET_NULL)
    rol = models.CharField(max_length=6, choices=Rols.choices(), blank=True, null=True)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellido)

    class Meta:
        ordering = ('id',)
        verbose_name_plural = 'Jugadores'

jugadores/forms.py
from django import forms
from .models import Jugador
from material import *

class JugadorForm(forms.ModelForm):
    layout = Layout('nombre', 'apellido',
                    Row('altura', 'peso', 'fnacimiento'),
                    'image', 'equipo',
                    Row('dorsal', 'posicion', 'rol'))
    class Meta:
        model = Jugador
        fields = '__all__'
        #labels = {'nombre': Nombre}  sirve para poner el titulo de cada input del formulario
        #widgets = {'nombre': forms.textInput(attrs={'class': 'form-control'}), forms.Select().....} para definir el tipo de input
                   

jugadores/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Jugador, Posicion
from stats.models import Estadistica
from equipos.models import Equipo

from .serializers import EstadisticasSerializer

from django.core import serializers

from .forms import JugadorForm

# Create your views here.   

class JugadorList(ListView):
    model = Jugador
    template_name = 'jugador_list.html'

    def get_context_data(self, **kwargs):
        title = "Administración de Jugadores"
        context = super().get_context_data(**kwargs)
        data = serializers.serialize('json', Jugador.objects.all())       
        context['equipos'] = data
        context['title'] = title
        return context

class JugadorDetail(DetailView):
    model = Jugador
    template_name = 'jugador_detail.html'
    context_object_name = 'jugador'

    def get_context_data(self, **kwargs):
        title = "Detalle Jugador"
        context = super().get_context_data(**kwargs) 

        stats = Estadistica.objects.filter(jugador=context['object'].id)
        estadisticas = serializers.serialize('json', stats)

        lista_partidos = [{
            'local': partido.partido.equipo_local,
            'visitante': partido.partido.equipo_visitante,
            'puntosLocal': partido.partido.puntos_local,
            'puntosVisitante': partido.partido.puntos_visitante,
            'puntos': partido.puntos,
            'asistencias': partido.asistencias,
            'rebotes': partido.rebotes,
            't2m': partido.t2m,
            't2f': partido.t2f,
            't3m': partido.t3m,
            't3f': partido.t3f,
            'tlm': partido.tlm,
            'tlf': partido.tlf,
            } for partido in stats]    
        
        lista_equipos = [{
            "local": equipo['local'].nombre,
            "visitante": equipo['visitante'].nombre,
            "puntosLocal": equipo['puntosLocal'],
            "puntosVisitante": equipo['puntosVisitante'],
            "puntos": equipo['puntos'],
            "asistencias": equipo['asistencias'],
            "rebotes": equipo['rebotes'],
            't2m': equipo['t2m'],
            't2f': equipo['t2f'],
            't3m': equipo['t3m'],
            't3f': equipo['t3f'],
            'tlm': equipo['tlm'],
            'tlf': equipo['tlf'],
            }for equipo in lista_partidos]


        lista_equipos = json.dumps(lista_equipos, ensure_ascii=False)
        
        print(lista_equipos)

        context['title'] = title
        context['estadisticas'] = estadisticas
        context['lista_equipos'] = lista_equipos
        return context

class JugadorCreate(CreateView):
    model = Jugador
    form_class = JugadorForm
    template_name = 'jugador_create.html'
    success_url = reverse_lazy('jugadores:list')

    def get_context_data(self, **kwargs):
        title = "Nuevo Jugador"
        context = super().get_context_data(**kwargs)
        context['title'] = title
        return context

class JugadorUpdate(UpdateView):
    model = Jugador
    form_class = JugadorForm
    template_name = 'jugador_create.html'
    success_url = reverse_lazy('jugadores:list')

    def get_context_data(self, **kwargs):
        title = "Editar Jugador"
        context = super().get_context_data(**kwargs)
        context['title'] = title
        return context

class JugadorDelete(DeleteView):
    model = Jugador
    success_url = reverse_lazy('jugadores:list')
    
    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

def update_db_field(request,pk):
    jugador = Jugador.objects.get(pk=pk)
    jugador.equipo = Equipo.objects.get(pk=1)
    jugador.save()
    return HttpResponseRedirect('/equipos/1')

jugadores/templates/jugador_create.html
{% extends "base.html" %}

{% load material_form %} 
{% load staticfiles %}

{% block page_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% include 'material/includes/material_css.html' %}
    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
{% endblock %}

{% block page_title %}{{ title }}{% endblock %}
{% block title %} - {{ title }}{% endblock %}
{% block page_content %}
    <div class="ballaverage-form">
        <h3>Edición de jugador</h3>
        <form method="POST" class="viewform" enctype="multipart/form-data">
            {% csrf_token %}
            {% form form=form %}{% endform %}
            <button type="submit" name="_submit" class="btn btn-primary btn-lg">Aceptar</button>
            <a style="margin-left: 2%;" href="{% url 'jugadores:list'  %}"><button type="button" class="btn btn-primary btn-lg">Cancelar</button></a>
        </form>
    </div>
{% endblock %}

jugadores/templates/jugador_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block page_head %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="manifest" href="{% static 'polymer/manifest.json' %}">
<script src="{% static 'polymer/bower_components/webcomponentsjs/webcomponents-loader.js' %}"></script>
<link rel="import" href="{% static 'polymer/src/ballaverage-app/player-card.html' %}">
<link rel="import" href="{% static 'polymer/src/ballaverage-app/stats-card.html' %}">
{% endblock %}

{% block page_title %}{{ title }}{% endblock %}
{% block title %} - {{ jugador.nombre }} {{ jugador.apellido }}{% endblock %}
{% block page_content %}
    <div class="stats">
        <player-card    
            nombre="{{ jugador.nombre }}"
            apellido="{{ jugador.apellido }}"
            altura="{{ jugador.altura }}"
            peso="{{ jugador.peso }}"
            fnacimiento="{{ jugador.fnacimiento|default:'No se ha defininido' }}"
            imagen="{{ jugador.image }}"
            rol="{{ jugador.get_rol_display|default:'Novato' }}"
            dorsal="{{ jugador.dorsal }}"
            equipo="{{jugador.equipo|default:'Sin equipo'}}"
            posicion="{{ jugador.posicion|default:'No se ha defininido' }}"
            estadisticas="{{estadisticas}}"
            
        ></player-card>
        <stats-card equipos="{{lista_equipos}}"></stats-card>
    </div>
{% endblock %}

jugadores/templates/jugador_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block page_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
    <link rel="manifest" href="{% static 'polymer/manifest.json' %}">
    
    <script src="{% static 'polymer/bower_components/webcomponentsjs/webcomponents-loader.js' %}"></script>
    
    <link rel="import" href="{% static 'polymer/src/ballaverage-app/jugadorlist-card.html' %}">
    <link rel="import" href="{% static 'polymer/src/ballaverage-app/ballaverage-app.html' %}">
    <link rel="import" href="{% static 'polymer/bower_components/paper-fab/paper-fab.html' %}">
{% endblock %}

{% block page_title %}{{ title }}{% endblock %}
{% block title %} - {{ title }}{% endblock %}

{% block page_content %}
    <div class="plantilla-container">
        {% for jugador in object_list %}
        <jugadorlist-card 
            nombre="{{ jugador.nombre }}"
            apellido="{{ jugador.apellido }}"
            posicion="{{ jugador.posicion|default:'Suplente' }}"
            dorsal="{{ jugador.dorsal }}"
            equipo="{{ jugador.equipo }}"
            altura="{{ jugador.altura }}"
            rol="{{ jugador.get_rol_display|default:'Novato' }}"
            editar="{% url 'jugadores:update' jugador.id %}"
            borrar="{% url 'jugadores:delete' jugador.id %}"
            imagen="{{ jugador.image }}"
            fichar="{% url 'jugadores:fichar' jugador.id %}"
        ></jugadorlist-card>
        {% empty %}
            <h2>No hay jugadores registrados</h2>
        {% endfor %}
    </div>
    <a href="{% url 'jugadores:new' %}"><paper-fab icon="add"></paper-fab></a>
{% endblock %}