BallAverage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/', include(('equipos.urls', 'equipos'), namespace='equipos')),
    path('jugadores/', include(('jugadores.urls', 'jugadores'), namespace='jugadores')),
    path('estadisticas/', include(('stats.urls', 'estadisticas'), namespace='estadisticas')),
    path('partidos/', include(('partidos.urls', 'partidos'), namespace='partidos')),
    path('', include(('login.urls', 'login'), namespace='login')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
'''Login Configuration'''
from django.urls import path, re_path, include
from django.conf.urls import url
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from . import views

urlpatterns = [
    path('', login, {'template_name':'index.html'}, name='login'),
    path('registrar/', views.RegistroUsuario.as_view(), name='registrar'),
    path('logout/', logout_then_login, name='logout'),
    path('reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html',
        'email_template_name':'registration/password_reset_email.html', 'post_reset_redirect':'login:password_reset_done'}, name='password_reset'),    
    path('reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'}, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', password_reset_confirm,
         {'template_name':'registration/password_reset_confirm.html','post_reset_redirect':'login:password_reset_complete'}, name='password_reset_confirm'),
    path('reset/done', password_reset_complete, {'template_name':'registration/password_reset_complete.html'}, name='password_reset_complete'),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistroForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username': 'Nombre de usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'email': 'E-mail',
        }
        help_texts = {
            'username': None,
            'email': 'ej: ballaverage@gmail.com'
        }

    def __init__(self, *args, **kwargs):
        super(RegistroForm, self).__init__(*args, **kwargs)

        self.fields['password1'].label = 'Contraseña'
        self.fields['password1'].help_text = 'Debe tener 8 caracteres alfanuméricos.'

        self.fields['password2'].label = 'Confirmar contraseña'
        self.fields['password2'].help_text = 'Introduce la misma contraseña, para su verificación.'

login/views.py
from django.views.generic import CreateView

from django.contrib.auth.models import User
from .forms import RegistroForm

from django.urls import reverse_lazy

# Create your views here.

class RegistroUsuario(CreateView):
    model = User
    form_class = RegistroForm
    template_name = 'registro_usuario.html'
    success_url = reverse_lazy('login:login') 

    def get_context_data(self, **kwargs):
        title = "Registro de usuarios"
        context = super().get_context_data(**kwargs)
        context['title'] = title
        return context

login/templates/index.html
{% extends "login.html" %}
{% load material_form %} 

{% block page_title %}BallAverage{% endblock %}
{% block page_content %}
  <div class="ballaverage-login">
      <div class="login-title">
        <h2>BallAverage</h2>
        <img id="img-login" src="media/login.png" alt="">
      </div>
        <form method="POST" class="viewform" enctype="multipart/form-data">
          
            {% csrf_token %}
            {% form form=form %}{% endform %}
            <br><a href="{% url 'login:password_reset' %}">Olvide mi contraseña</a><br><br>
            <button type="submit" name="_submit" class="btn btn-primary btn-lg">Entrar</button>
            <a href="{% url 'login:registrar' %}">Registrarse</a>
        </form>
  </div>
{% endblock %}

login/templates/registro_usuario.html
{% extends "login.html" %}
{% load material_form %} 

{% block page_title %}Registro de usuarios{% endblock %}
{% block page_content %}
    <div class="ballaverage-register">
        <h2>Registro BallAverage</h2>
        <form method="POST" class="viewform" enctype="multipart/form-data">
            {% csrf_token %}
            {% form form=form %}{% endform %}
            <button type="submit" name="_submit" class="btn btn-primary btn-lg">Registrar</button>
            <a style="margin-left: 2%;" href="{% url 'login:login' %}"><button type="button" class="btn btn-primary btn-lg">Cancelar</button></a>
        </form>
    </div>
{% endblock %}