BallAverage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/', include(('equipos.urls', 'equipos'), namespace='equipos')),
    path('jugadores/', include(('jugadores.urls', 'jugadores'), namespace='jugadores')),
    path('estadisticas/', include(('stats.urls', 'estadisticas'), namespace='estadisticas')),
    path('partidos/', include(('partidos.urls', 'partidos'), namespace='partidos')),
    path('', include(('login.urls', 'login'), namespace='login')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipos/urls.py
'''Equipo Configuration'''
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', login_required(views.EquipoList.as_view()), name='list'),
    path('new', login_required(views.EquipoCreate.as_view()), name="new"),
    path('<pk>', login_required(views.EquipoDetail.as_view()), name="detail"),
    path('update/<pk>', login_required(views.EquipoUpdate.as_view()), name="update"),
    path('delete/<pk>', login_required(views.EquipoDelete.as_view()), name="delete"),
    path('baja/<pk>/<id_equipo>', login_required(views.update_db_field), name="quitar"),
]

login/urls.py
'''Login Configuration'''
from django.urls import path, re_path, include
from django.conf.urls import url
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from . import views

urlpatterns = [
    path('', login, {'template_name':'index.html'}, name='login'),
    path('registrar/', views.RegistroUsuario.as_view(), name='registrar'),
    path('logout/', logout_then_login, name='logout'),
    path('reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html',
        'email_template_name':'registration/password_reset_email.html', 'post_reset_redirect':'login:password_reset_done'}, name='password_reset'),    
    path('reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'}, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', password_reset_confirm,
         {'template_name':'registration/password_reset_confirm.html','post_reset_redirect':'login:password_reset_complete'}, name='password_reset_confirm'),
    path('reset/done', password_reset_complete, {'template_name':'registration/password_reset_complete.html'}, name='password_reset_complete'),
]

equipos/models.py
from django.db import models

# Create your models here.

class Equipo(models.Model):
    '''Prueba modelo'''
    nombre = models.CharField(max_length=50)
    localidad = models.CharField(max_length=25)
    web = models.CharField(max_length=50, blank=True)
    campo = models.CharField(max_length=50, blank=True)
    image = models.ImageField(null=True, blank=True, default='equipo_default.jpg')

    def __str__(self):
        return self.nombre
        
    class Meta:
        ordering = ('id',)
        

equipos/forms.py
from django import forms
from .models import Equipo
from material import *

class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = '__all__'
        #labels = {'nombre': Nombre}  sirve para poner el titulo de cada input del formulario
        #widgets = {'nombre': forms.textInput(attrs={'class': 'form-control'}), forms.Select().....} para definir el tipo de input

equipos/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import EquipoForm
from .models import Equipo

from django.core import serializers

from jugadores.models import Jugador

# Create your views here.
'''
def serializar_equipo(request):
    data = serializers.serialize('json', Equipo.objects.all())
    return HttpResponse(data, content_type='application/json')
'''
class EquipoList(ListView):
    model = Equipo
    template_name = 'equipo_list.html'

    def get_context_data(self, **kwargs):
        title = "Administración de Equipos"
        context = super().get_context_data(**kwargs)
        data = serializers.serialize('json', Equipo.objects.all())       
        context['equipos'] = data
        context['title'] = title
        return context

class EquipoDetail(DetailView):
    model = Equipo
    template_name = 'equipo_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = "Plantilla {}".format(context['object'].nombre) 
        jugadores = Jugador.objects.filter(equipo=context['object'].id)
        context['title'] = title
        context['jugadores'] = jugadores
        return context

class EquipoCreate(CreateView):
    model = Equipo
    form_class = EquipoForm
    template_name = 'equipo_create.html'
    success_url = reverse_lazy('equipos:list')

    def get_context_data(self, **kwargs):
        title = "Nuevo Equipo"
        context = super().get_context_data(**kwargs)
        context['title'] = title
        return context

class EquipoUpdate(UpdateView):
    model = Equipo
    form_class = EquipoForm
    template_name = 'equipo_create.html'
    success_url = reverse_lazy('equipos:list')

    def get_context_data(self, **kwargs):
        title = "Editar Equipo"
        context = super().get_context_data(**kwargs)
        context['title'] = title
        return context

class EquipoDelete(DeleteView):
    model = Equipo
    success_url = reverse_lazy('equipos:list')
    
    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

def update_db_field(request,pk,id_equipo):
    jugador = Jugador.objects.get(pk=pk)
    jugador.equipo = None
    jugador.save()
    return HttpResponseRedirect('/equipos/' + id_equipo)

equipos/templates/equipo_create.html
{% extends "base.html" %}

{% load material_form %} 
{% load staticfiles %}

{% block page_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% include 'material/includes/material_css.html' %}
    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
{% endblock %}

{% block page_title %}{{ title }}{% endblock %}
{% block title %} - {{ title }}{% endblock %}
{% block page_content %}
    <div class="ballaverage-form">
        <h3>Edición de equipo</h3>
        <form method="POST" class="viewform" enctype="multipart/form-data">
            {% csrf_token %}
            {% form form=form %}{% endform %}
            <button type="submit" name="_submit" class="btn btn-primary btn-lg">Aceptar</button>
            <a style="margin-left: 2%;" href="{% url 'equipos:list' %}"><button type="button" class="btn btn-primary btn-lg">Cancelar</button></a>
        </form>
    </div>
{% endblock %}

equipos/templates/equipo_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block page_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="manifest" href="{% static 'polymer/manifest.json' %}">
    <script src="{% static 'polymer/bower_components/webcomponentsjs/webcomponents-loader.js' %}"></script>
    <link rel="import" href="{% static 'polymer/src/ballaverage-app/plantilla-card.html' %}">
{% endblock %}

{% block page_title %}{{ title }}{% endblock %}
{% block title %} - {{ title }}{% endblock %}

{% block page_content %}
    <div class="plantilla-container">
        {% for jugador in jugadores %}
                <plantilla-card 
                    nombre="{{ jugador.nombre }}"
                    apellido="{{ jugador.apellido }}"
                    posicion="{{ jugador.posicion|default:'Suplente' }}"
                    dorsal="{{ jugador.dorsal }}"
                    equipo="{{ jugador.equipo }}"
                    borrar="{% url 'equipos:quitar' jugador.id equipo.id %}"
                    estadisticas="{% url 'jugadores:detail' jugador.id %}"
                    imagen="{{ jugador.image }}"
                ></plantilla-card>
        {% empty %}
            <h2>No hay jugadores en este equipo</h2>
        {% endfor %}
    </div>
{% endblock %}

equipos/templates/equipo_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block page_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
    <link rel="manifest" href="{% static 'polymer/manifest.json' %}">
    
    <script src="{% static 'polymer/bower_components/webcomponentsjs/webcomponents-loader.js' %}"></script>
    
    <link rel="import" href="{% static 'polymer/src/ballaverage-app/team-card.html' %}">
    <link rel="import" href="{% static 'polymer/src/ballaverage-app/ballaverage-app.html' %}">
    <link rel="import" href="{% static 'polymer/bower_components/paper-fab/paper-fab.html' %}">
{% endblock %}

{% block page_title %}{{ title }}{% endblock %}
{% block title %} - {{ title }}{% endblock %}

{% block page_content %}
    <div class="container">
        {% for equipo in object_list %}
            <div>
                <team-card
                    nombre="{{ equipo.nombre.upper }}"
                    imagen="{{ equipo.image.url }}"
                    localidad="{{ equipo.localidad }}"
                    campo="{{equipo.campo|default:'No se ha defininido'}}"
                    web="{{equipo.web|default:'No se ha defininido' }}"
                    plantilla="{% url 'equipos:detail' equipo.id %}"
                    editar="{% url 'equipos:update' equipo.id %}"
                    borrar="{% url 'equipos:delete' equipo.id %}"
                ></team-card>
            </div>
        {% empty %}
            <h2>No hay equipos registrados</h2>
        {% endfor %}
    </div>
    <a href="{% url 'equipos:new' %}"><paper-fab icon="add"></paper-fab></a>
{% endblock %}